<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli') exit;
require dirname(__DIR__).'/app/bootstrap.php';
require ROOT.'/app/Reports.php';
require ROOT.'/app/Backup.php';
set_error_handler(function($severity,$message,$file,$line) { if(!(error_reporting() & $severity)) return true; throw new ErrorException($message,0,$severity,$file,$line); });
$passed=0;
function check(bool $condition,string $message): void { global $passed; if(!$condition) throw new RuntimeException('FAIL: '.$message); $passed++; echo "PASS $message\n"; }
function denied(callable $fn,int $code,string $message): void { try { $fn(); } catch(DomainException $e) { check($e->getCode()===$code,$message.' ('.$e->getCode().')'); return; } throw new RuntimeException('FAIL: '.$message.' was permitted'); }
$name='daloy_test_'.bin2hex(random_bytes(5));
$server=new PDO(preg_replace('/;?dbname=[^;]+/','',$config['dsn']),$config['username'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
$server->exec("CREATE DATABASE `$name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
$testConfig=$config; $testConfig['dsn']=preg_replace('/dbname=[^;]+/','dbname='.$name,$config['dsn']); $testConfig['session_path']=ROOT.'/storage/'.$name.'-sessions';
$configFile=ROOT.'/storage/'.$name.'.php'; file_put_contents($configFile,'<?php return '.var_export($testConfig,true).';');
$process=null; $browser=null; $log=ROOT.'/storage/'.$name.'.log'; $cookies=[]; $failed=false; $restoreName=null; $testFiles=[];
try {
    $db=new Database($testConfig); foreach(explode(';',file_get_contents(ROOT.'/database/schema.sql')) as $statement) if(trim($statement)!=='') $db->pdo->exec($statement);
    foreach(['write_lock'=>'1','organization'=>'Test SDO Aurora','system_notice'=>''] as $k=>$v) $db->insert('system_settings',['setting_key'=>$k,'setting_value'=>$v]);
    $password='Test-workforce-'.bin2hex(random_bytes(8));
    $makeUser=function(string $role,string $label) use($db,$password): array { $id=$db->insert('users',['name'=>$label,'email'=>strtolower(str_replace(' ','',$label)).'@example.test','role'=>$role,'password_hash'=>password_hash($password,PASSWORD_DEFAULT),'must_change_password'=>0,'skills'=>'First aid, Basic life support','created_at'=>now()]); return $db->one('SELECT * FROM users WHERE id=?',[$id]); };
    $admin=$makeUser('admin','Test Admin'); $head=$makeUser('head','Test Head'); $n1=$makeUser('nurse','Nurse One'); $n2=$makeUser('nurse','Nurse Two'); $n3=$makeUser('nurse','Nurse Three');
    $as=new Service($db,$admin); $hs=new Service($db,$head); $ns=new Service($db,$n1); $n2s=new Service($db,$n2);
    $district=$as->catalog(['table'=>'districts','name'=>'Test District','active'=>1]);
    $municipality=$as->catalog(['table'=>'municipalities','name'=>'Test Municipality','active'=>1]);
    $location=$as->catalog(['table'=>'locations','name'=>'Test School','active'=>1,'type'=>'School','district_id'=>$district,'municipality_id'=>$municipality,'required_nurses'=>2]);
    $duty=$as->catalog(['table'=>'duty_types','name'=>'School Health','active'=>1]); $reason=$as->catalog(['table'=>'deployment_reasons','name'=>'Medical Assistance','active'=>1]);
    $shift=$as->catalog(['table'=>'shifts','name'=>'Night','active'=>1,'start_time'=>'22:00','end_time'=>'06:00']);
    check($shift>0,'Configurable district, municipality, location, duty, reason and shift');
    $base=['nurse_id'=>$n1['id'],'location_id'=>$location,'duty_type_id'=>$duty,'starts_at'=>'2035-01-10T08:00','ends_at'=>'2035-01-10T17:00','remarks'=>'<script>alert("x")</script>'];
    $schedule=$ns->schedule($base); check($schedule>0,'Nurse creates own schedule');
    denied(fn()=>$ns->schedule($base),409,'Overlapping schedule blocked');
    denied(fn()=>$ns->schedule(array_merge($base,['nurse_id'=>$n2['id']])),403,'Nurse cannot create another nurse’s schedule');
    denied(fn()=>$ns->schedule(array_merge($base,['starts_at'=>'2035-02-30T08:00'])),422,'Invalid calendar dates blocked');
    denied(fn()=>$ns->schedule(array_merge($base,['ends_at'=>$base['starts_at']])),422,'Zero-length interval blocked');
    $touching=$ns->schedule(array_merge($base,['starts_at'=>'2035-01-10T17:00','ends_at'=>'2035-01-10T18:00'])); check($touching>0,'Back-to-back assignments allowed');
    $overnight=$ns->schedule(array_merge($base,['starts_at'=>'2035-01-11T22:00','ends_at'=>'2035-01-12T06:00'])); check($overnight>0,'Overnight schedule accepted');
    denied(fn()=>$ns->schedule(array_merge($base,['starts_at'=>'2035-01-12T05:00','ends_at'=>'2035-01-12T07:00'])),409,'Cross-midnight overlap blocked');
    $ns->schedule(array_merge($base,['id'=>$schedule,'remarks'=>'Updated <script>alert(1)</script>'])); check(true,'Editing excludes the record itself from conflicts');
    $schedule2=$n2s->schedule(array_merge($base,['nurse_id'=>$n2['id']]));
    denied(fn()=>$ns->cancel(['table'=>'schedules','id'=>$schedule2,'reason'=>'Tamper']),403,'Nurse cannot cancel another nurse’s schedule');
    $leave=$ns->leave(['starts_at'=>'2035-01-10T08:00','ends_at'=>'2035-01-10T17:00','type'=>'Vacation Leave','reason'=>'Test']);
    denied(fn()=>$ns->reviewLeave(['id'=>$leave,'status'=>'Approved']),403,'Nurse cannot approve leave');
    denied(fn()=>$hs->reviewLeave(['id'=>$leave,'status'=>'Approved']),409,'Approval cannot overlap scheduled duty');
    check($as->record('leave_records',$leave)['status']==='Submitted','Failed approval rolled back');
    $ns->cancel(['table'=>'schedules','id'=>$schedule,'reason'=>'Leave approved after rescheduling']);
    $hs->reviewLeave(['id'=>$leave,'status'=>'Approved','review_note'=>'Approved by head']);
    denied(fn()=>$ns->schedule($base),409,'Approved leave blocks schedule');
    denied(fn()=>$ns->cancel(['table'=>'leave_records','id'=>$leave,'reason'=>'Bypass']),403,'Nurse cannot revoke approved leave');
    $aBase=['title'=>'Test Outreach','location_id'=>$location,'starts_at'=>'2035-01-10T08:00','ends_at'=>'2035-01-10T17:00','required_nurses'=>1,'required_skill'=>'First aid','reason_id'=>$reason,'instructions'=>'Bring supplies'];
    $activity=$hs->activity($aBase); $candidates=$hs->candidates($activity);
    check(count($candidates)===3,'Candidates include unavailable personnel');
    check(!$candidates[0]['eligible'] || !$candidates[1]['eligible'],'Candidate list explains conflicts');
    denied(fn()=>$hs->deploy(['activity_id'=>$activity,'nurse_id'=>$n1['id']]),409,'Leave blocks deployment');
    denied(fn()=>$hs->deploy(['activity_id'=>$activity,'nurse_id'=>$n2['id']]),409,'Duty blocks deployment');
    denied(fn()=>$ns->deploy(['activity_id'=>$activity,'nurse_id'=>$n3['id']]),403,'Nurse cannot authorize deployment');
    $deployment=$hs->deploy(['activity_id'=>$activity,'nurse_id'=>$n3['id']]); check($deployment>0,'Supervisor deploys eligible nurse');
    check((bool)$db->one('SELECT id FROM notifications WHERE user_id=?',[$n3['id']]),'Deployment notification created');
    denied(fn()=>$hs->deploy(['activity_id'=>$activity,'nurse_id'=>$n3['id']]),409,'Staffing capacity cannot be exceeded');
    denied(fn()=>$ns->acknowledge(['id'=>$deployment]),403,'Nurse cannot acknowledge another nurse’s deployment');
    $n3s=new Service($db,$n3); $n3s->acknowledge(['id'=>$deployment]); $ack=$as->record('deployments',$deployment)['acknowledged_at']; $n3s->acknowledge(['id'=>$deployment]);
    check($ack!==null && $as->record('deployments',$deployment)['acknowledged_at']===$ack,'Acknowledgment is timestamped and idempotent');
    denied(fn()=>$hs->activity(array_merge($aBase,['id'=>$activity,'title'=>'Rewrite'])),409,'Requirement with deployment history is immutable');
    denied(fn()=>$hs->cancel(['table'=>'activities','id'=>$activity,'reason'=>'Cancel']),409,'Activity cannot be cancelled with live assignments');
    $hs->cancel(['table'=>'deployments','id'=>$deployment,'reason'=>'Activity rescheduled']); check($as->record('deployments',$deployment)['acknowledged_at']===$ack,'Cancellation preserves acknowledgment history');
    denied(fn()=>$n3s->acknowledge(['id'=>$deployment]),409,'Cancelled deployment cannot be acknowledged');
    $skillActivity=$hs->activity(array_merge($aBase,['title'=>'Advanced competency','required_skill'=>'Advanced trauma certification']));
    denied(fn()=>$hs->deploy(['activity_id'=>$skillActivity,'nurse_id'=>$n3['id']]),422,'Missing competency blocks deployment');
    $locationData=$as->record('locations',$location); $as->catalog(array_merge($locationData,['table'=>'locations','active'=>0]));
    check(in_array('Destination is inactive',$hs->candidates($activity)[0]['reasons'],true),'Candidate list flags inactive destination');
    denied(fn()=>$hs->deploy(['activity_id'=>$activity,'nurse_id'=>$n3['id']]),422,'Inactive location blocks deployment');
    $as->catalog(array_merge($locationData,['table'=>'locations','active'=>1]));
    $available=$ns->availability(['starts_at'=>'2035-01-15T08:00','ends_at'=>'2035-01-15T17:00','status'=>'Unavailable','reason'=>'Authorized unavailability']);
    denied(fn()=>$ns->schedule(array_merge($base,['starts_at'=>'2035-01-15T09:00','ends_at'=>'2035-01-15T10:00'])),409,'Unavailability blocks assignments');
    denied(fn()=>$ns->availability(['starts_at'=>'2035-01-15T09:00','ends_at'=>'2035-01-15T10:00','status'=>'Available']),409,'Available flag cannot bypass a blocker');
    $ns->cancel(['table'=>'availability_records','id'=>$available,'reason'=>'Available again']);
    check(!$ns->conflicts((int)$n1['id'],'2035-01-15 08:00:00','2035-01-15 17:00:00'),'Cancellation recalculates eligibility');
    denied(fn()=>$ns->catalog(['table'=>'districts','name'=>'Unauthorized','active'=>1]),403,'Configuration restricted to administrator');
    denied(fn()=>$hs->saveUser([]),403,'Supervisor cannot administer accounts');
    denied(fn()=>$as->saveUser(['id'=>$admin['id'],'role'=>'admin','active'=>0]),422,'Administrator cannot deactivate self');
    denied(fn()=>$ns->candidates($activity),403,'Candidate list restricted to managers');
    $raceActivity=$hs->activity(array_merge($aBase,['title'=>'Concurrent staffing','starts_at'=>'2035-01-25T08:00','ends_at'=>'2035-01-25T17:00']));
    $workerEnv=getenv(); $workerEnv['DALOY_CONFIG_FILE']=$configFile; $workers=[];
    foreach([$n2['id'],$n3['id']] as $candidate) {
        $worker=proc_open([PHP_BINARY,ROOT.'/tests/deploy_worker.php',(string)$head['id'],(string)$raceActivity,(string)$candidate],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$workerPipes,ROOT,$workerEnv);
        if(!is_resource($worker)) throw new RuntimeException('Could not start concurrency test.'); fclose($workerPipes[0]); $workers[]=[$worker,$workerPipes];
    }
    $results=[]; foreach($workers as [$worker,$workerPipes]) { $results[]=stream_get_contents($workerPipes[1]); $stderr=stream_get_contents($workerPipes[2]); fclose($workerPipes[1]); fclose($workerPipes[2]); if(proc_close($worker)!==0) throw new RuntimeException($stderr); }
    sort($results); check($results===['assigned','blocked:409'],'Concurrent deployment cannot overfill the same requirement');
    $filter=['starts_at'=>'2035-01-01 00:00','ends_at'=>'2035-02-01 00:00'];
    foreach($ns->roster($filter) as $r) check($r['nurse_id']===$n1['id'],'Personal roster excludes other nurses');
    foreach(Reports::TYPES as $key=>$label) { $report=Reports::build($as,$key,$filter); check(isset($report['columns'],$report['rows']),'Report: '.$label); }
    denied(fn()=>Reports::build($ns,'daily',$filter),403,'Nurse cannot export protected reports');
    denied(fn()=>Reports::build($hs,'audit',$filter),403,'Audit access restricted to administrator');
    $report=['columns'=>['Name','Value'],'rows'=>[['José','<script>'],['=HYPERLINK("bad")',str_repeat('Long text ',300)]]];
    $xlsx=Reports::xlsx($report,'Test export'); check(str_starts_with($xlsx,'PK'),'Excel export is an actual XLSX archive');
    $xlsxFile=ROOT.'/storage/'.$name.'.xlsx'; file_put_contents($xlsxFile,$xlsx); $zip=new ZipArchive(); $zip->open($xlsxFile); $xml=$zip->getFromName('xl/worksheets/sheet1.xml');
    check((bool)simplexml_load_string($xml) && !str_contains($xml,'<f>') && str_contains($xml,'José'),'XLSX preserves Unicode and treats formulas as text'); $zip->close(); unlink($xlsxFile);
    $pdf=Reports::pdf($report,'Test PDF'); check(str_starts_with($pdf,'%PDF-1.4') && str_ends_with($pdf,'%%EOF'),'PDF export generated');
    $audits=$db->all('SELECT * FROM audit_logs'); check(count($audits)>20,'Mutations generate audit records');
    check(!str_contains(json_encode($audits),'password_hash'),'Audit records omit password hashes');
    $secondSchool=$as->catalog(['table'=>'locations','name'=>'Second Public School','active'=>1,'type'=>'School','municipality_id'=>$municipality,'required_nurses'=>0]);
    $thirdSchool=$as->catalog(['table'=>'locations','name'=>'Third Public School','active'=>1,'type'=>'School','municipality_id'=>$municipality,'required_nurses'=>0]);
    $schoolAccount=array_merge($n3,['location_id'=>$location,'school_ids'=>[$secondSchool,$thirdSchool,$secondSchool],'schools_present'=>'1']);
    $as->saveUser($schoolAccount);
    check(count($as->assignedLocations((int)$n3['id']))===3,'One nurse has a home school and multiple additional schools without duplicates');
    $as->saveUser($n3+['location_id'=>$location]);
    check(count($db->all('SELECT * FROM nurse_locations WHERE nurse_id=?',[$n3['id']]))===2,'Account updates without school inputs preserve assignments');
    $invalidSchool=array_merge($schoolAccount,['school_ids'=>[$secondSchool,'invalid']]);
    denied(fn()=>$as->saveUser($invalidSchool),422,'Invalid school assignments are rejected');
    check(count($db->all('SELECT * FROM nurse_locations WHERE nurse_id=?',[$n3['id']]))===2,'Invalid assignment update leaves existing schools intact');
    $office=$as->catalog(['table'=>'locations','name'=>'Test Office','type'=>'SDO Office','active'=>1,'required_nurses'=>0]);
    denied(fn()=>$as->saveUser(array_merge($schoolAccount,['school_ids'=>[$office]])),422,'Additional school assignments reject non-school venues');
    $as->saveUser(array_merge($schoolAccount,['school_ids'=>[]]));
    check(count($as->assignedLocations((int)$n3['id']))===1,'Additional schools can be cleared while keeping the home school');
    $as->saveUser($schoolAccount);
    $report=Reports::build($as,'availability',$filter+['nurse_id'=>$n3['id'],'location_id'=>$secondSchool]);
    check(count($report['rows'])===1 && str_contains($report['rows'][0][2],'Third Public School'),'Availability report filters and displays additional schools');
    $as->schedule(array_merge($base,['nurse_id'=>$n3['id'],'location_id'=>$secondSchool,'starts_at'=>'2035-03-01T08:00','ends_at'=>'2035-03-01T12:00']));
    $as->schedule(array_merge($base,['nurse_id'=>$n3['id'],'location_id'=>$thirdSchool,'starts_at'=>'2035-03-01T13:00','ends_at'=>'2035-03-01T17:00']));
    check(count($as->roster(['nurse_id'=>$n3['id'],'starts_at'=>'2035-03-01T00:00','ends_at'=>'2035-03-02T00:00']))===2,'One nurse can have duties at two schools on the same day');
    denied(fn()=>$as->schedule(array_merge($base,['nurse_id'=>$n3['id'],'location_id'=>$thirdSchool,'starts_at'=>'2035-03-01T09:00','ends_at'=>'2035-03-01T11:00'])),409,'Multiple assigned schools still prevent overlapping duties');
    $as->schedule(array_merge($base,['nurse_id'=>$n3['id'],'location_id'=>$secondSchool,'starts_at'=>'2035-03-31T23:00','ends_at'=>'2035-04-01T01:00']));
    $cancelledMonthly=$as->schedule(array_merge($base,['nurse_id'=>$n3['id'],'location_id'=>$thirdSchool,'starts_at'=>'2035-04-02T08:00','ends_at'=>'2035-04-02T12:00']));
    $as->cancel(['table'=>'schedules','id'=>$cancelledMonthly,'reason'=>'Monthly count test']);
    $monthly=$as->monthlyNurseSchedules('2035-03');
    check(count($monthly)===1 && (int)$monthly[0]['id']===(int)$n3['id'] && (int)$monthly[0]['duty_count']===3,'Monthly nurse ranking counts each schedule once, including multiple schools');
    check($as->monthlyNurseSchedules('2035-04')===[],'Monthly counts exclude cancelled schedules and duties starting in the previous month');
    denied(fn()=>$as->monthlyNurseSchedules('2035-13'),422,'Monthly graph rejects invalid months');
    denied(fn()=>$ns->monthlyNurseSchedules('2035-03'),403,'Workforce ranking is restricted to managers');
    $backupAttachment=bin2hex(random_bytes(24)).'.pdf'; $attachmentPath=ROOT.'/storage/uploads/'.$backupAttachment;
    if(!is_dir(dirname($attachmentPath))) mkdir(dirname($attachmentPath),0700,true);
    $attachmentBytes=Reports::pdf(['columns'=>['Note'],'rows'=>[['Recovery test']]],'Recovery fixture'); file_put_contents($attachmentPath,$attachmentBytes); $testFiles[]=$attachmentPath;
    $db->update('leave_records',$leave,['attachment'=>$backupAttachment]);
    $backupFile=ROOT.'/storage/'.$name.'.zip'; Backup::create($db,$backupFile); unlink($attachmentPath);
    $restoreName='daloy_test_'.bin2hex(random_bytes(5)); $server->exec("CREATE DATABASE `$restoreName` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
    $restoreConfig=$testConfig; $restoreConfig['dsn']=preg_replace('/dbname=[^;]+/','dbname='.$restoreName,$testConfig['dsn']); $restored=new Database($restoreConfig);
    Backup::restore($restored,$backupFile);
    foreach(Backup::TABLES as $table) check($restored->one("SELECT COUNT(*) n FROM $table")['n']===$db->one("SELECT COUNT(*) n FROM $table")['n'],'Backup / restore: '.$table);
    check(is_file($attachmentPath) && hash_file('sha256',$attachmentPath)===hash('sha256',$attachmentBytes),'Backup restores missing protected attachment with original checksum');
    $db->update('leave_records',$leave,['attachment'=>null]);
    $refused=false; try { Backup::restore($restored,$backupFile); } catch(RuntimeException $e) { $refused=true; } check($refused,'Restore refuses to overwrite an existing database'); unlink($backupFile);
    // Run the real HTTP entry points against the isolated MariaDB database.
    $port=random_int(19000,24000); $baseUrl='http://127.0.0.1:'.$port.'/';
    $env=getenv(); $env['DALOY_CONFIG_FILE']=$configFile;
    if(!is_dir($testConfig['session_path'])) mkdir($testConfig['session_path'],0700,true);
    $process=proc_open([PHP_BINARY,'-d','upload_tmp_dir='.$testConfig['session_path'],'-S','127.0.0.1:'.$port,'-t',ROOT],[0=>['pipe','r'],1=>['file',$log,'a'],2=>['file',$log,'a']],$pipes,ROOT,$env);
    if(!is_resource($process)) throw new RuntimeException('Could not start test server.'); fclose($pipes[0]);
    $ready=false; for($i=0;$i<50;$i++) { $sock=@fsockopen('127.0.0.1',$port,$eno,$estr,.1); if($sock) { fclose($sock); $ready=true; break; } usleep(100000); }
    check($ready,'Isolated HTTP server started');
    function request(string $session,string $path='',?array $data=null): array {
        global $baseUrl,$cookies,$name;
        $cookies[$session]??=ROOT.'/storage/'.$name.'-'.$session.'.cookie';
        $c=curl_init($baseUrl.$path); curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_COOKIEFILE=>$cookies[$session],CURLOPT_COOKIEJAR=>$cookies[$session],CURLOPT_TIMEOUT=>15,CURLOPT_HEADER=>true]);
        if($data!==null) { curl_setopt($c,CURLOPT_POST,true); $multipart=(bool)array_filter($data,fn($v)=>$v instanceof CURLFile); curl_setopt($c,CURLOPT_POSTFIELDS,$multipart?$data:http_build_query($data)); }
        $raw=curl_exec($c); if($raw===false) throw new RuntimeException(curl_error($c)); $code=curl_getinfo($c,CURLINFO_RESPONSE_CODE); $size=curl_getinfo($c,CURLINFO_HEADER_SIZE); curl_close($c); return ['status'=>$code,'headers'=>substr($raw,0,$size),'body'=>substr($raw,$size)];
    }
    function token(array $r): string { if(!preg_match('/name="csrf" value="([a-f0-9]+)"/',$r['body'],$m)) throw new RuntimeException('CSRF token not found: '.substr($r['body'],0,200)); return $m[1]; }
    $login=request('admin'); check($login['status']===200 && str_contains($login['body'],'Welcome back'),'Login page renders');
    check(str_contains($login['headers'],'Content-Security-Policy:') && str_contains(strtolower($login['headers']),'httponly'),'CSP and HttpOnly session cookie present');
    check(request('admin','',['action'=>'login','email'=>$admin['email'],'password'=>$password])['status']===419,'Missing CSRF rejected');
    check(request('admin','',['csrf'=>token($login),'action'=>'login','email'=>$admin['email'],'password'=>$password])['status']===303,'Administrator signs in');
    $pageHeadings=['dashboard'=>'Your workforce, in flow.','schedule'=>'Master schedule','calendar'=>'Workforce calendar','availability'=>'Availability','deployment'=>'Deployment center','leave'=>'Leave & unavailability','notifications'=>'Notifications','profile'=>'My profile','users'=>'User accounts','nurses'=>'Nursing personnel','locations'=>'Schools & duty locations','activities'=>'Activities & events','reports'=>'Reports','audit'=>'Audit trail','settings'=>'Workspace settings','configuration'=>'Configuration'];
    foreach($pageHeadings as $page=>$heading) {
        $r=request('admin','?page='.$page); check($r['status']===200 && str_contains($r['body'],'data-page="'.$page.'"') && str_contains($r['body'],'<h1>'.e($heading).'</h1>'),'HTTP link opens its own page: '.$page);
    }
    foreach(['schedule&new=1','schedule&edit='.$touching,'activities&new=1','activities&edit='.$skillActivity,'deployment&activity='.$activity,'leave&new=1','availability&new=1','users&new=1','users&edit='.$n1['id'],'locations&new=1','locations&edit='.$location,'configuration&tab=shifts&new=1','calendar&view=week&date=2035-01-10','calendar&view=day&date=2035-01-10','calendar&view=month&date=2035-01-10'] as $page) check(request('admin','?page='.$page)['status']===200,'HTTP editor / view: '.$page);
    check(str_contains(request('admin','?page=calendar&view=month&date=2035-01-31')['body'],'date=2035-02-01'),'Month navigation does not skip February from January 31');
    $r=request('admin','?page=schedule&from=2035-01-01&to=2035-01-31&status=Cancelled'); check(str_contains($r['body'],'&lt;script&gt;') && !str_contains($r['body'],'<script>alert'),'Stored remarks are HTML escaped');
    foreach(['pdf','xlsx','print'] as $fmt) { $r=request('admin','export.php?type=monthly&from=2035-01-01&to=2035-01-31&format='.$fmt); check($r['status']===200 && strlen($r['body'])>100,'HTTP export: '.$fmt); }
    $login=request('nurse'); check(request('nurse','',['csrf'=>token($login),'action'=>'login','email'=>$n1['email'],'password'=>$password])['status']===303,'Nurse signs in');
    check(request('nurse','?page=users')['status']===403,'Nurse cannot open user administration');
    check(request('nurse','?page=schedule&edit='.$schedule2)['status']===403,'Nurse cannot open another nurse’s editor');
    check(request('nurse','api.php?action=conflicts&nurse_id='.$n2['id'].'&starts_at=2035-01-01T08:00&ends_at=2035-01-01T17:00')['status']===403,'Conflict API enforces ownership');
    check(request('nurse','export.php?type=monthly&from=2035-01-01&to=2035-01-31')['status']===403,'HTTP export enforces role');
    check(request('nurse','download.php?type=leave&id='.$leave)['status']===404,'Absent attachment does not expose files');
    $r=request('nurse'); $csrf=token($r);
    $post=array_merge($base,['csrf'=>$csrf,'action'=>'schedule','starts_at'=>'2035-01-20T08:00','ends_at'=>'2035-01-20T17:00','return'=>'?page=schedule']);
    check(request('nurse','?page=schedule&new=1',$post)['status']===303,'Nurse creates schedule through HTTP');
    check(request('nurse','?page=schedule&new=1',$post)['status']===409,'HTTP schedule conflict returns 409');
    $otherLogin=request('nurseOther'); request('nurseOther','',['csrf'=>token($otherLogin),'action'=>'login','email'=>$n1['email'],'password'=>$password]);
    $newPassword='Changed-password-12345';
    check(request('nurse','?page=profile',['csrf'=>$csrf,'action'=>'profile','phone'=>'09123456789','current_password'=>$password,'new_password'=>$newPassword,'confirm_password'=>$newPassword,'return'=>'?page=profile'])['status']===303,'Password change succeeds through HTTP');
    check(password_verify($newPassword,$as->record('users',(int)$n1['id'])['password_hash']),'New password stored as a hash');
    check(str_contains(request('nurseOther')['body'],'Welcome back'),'Password change invalidates existing sessions');
    $db->update('users',(int)$n2['id'],['must_change_password'=>1]); $login=request('newnurse'); request('newnurse','',['csrf'=>token($login),'action'=>'login','email'=>$n2['email'],'password'=>$password]);
    $r=request('newnurse'); check($r['status']===303 && str_contains($r['headers'],'Location: ?page=activate'),'Temporary password redirects to explicit account setup');
    check(request('newnurse','api.php?action=candidates&activity_id='.$activity)['status']===403,'Unactivated account cannot call API');
    $freshAdmin=$makeUser('admin','First Login Admin'); $db->update('users',(int)$freshAdmin['id'],['must_change_password'=>1,'phone'=>'09999999999']);
    $login=request('freshAdmin'); $r=request('freshAdmin','',['csrf'=>token($login),'action'=>'login','email'=>$freshAdmin['email'],'password'=>$password]);
    check($r['status']===303 && str_contains($r['headers'],'Location: ?page=activate'),'First sign-in goes directly to account setup');
    foreach(array_keys($pageHeadings) as $page) { $r=request('freshAdmin','?page='.$page); check($r['status']===303 && str_contains($r['headers'],'Location: ?page=activate'),'Incomplete account redirects explicitly from '.$page); }
    $r=request('freshAdmin','?page=activate');
    check($r['status']===200 && str_contains($r['body'],'id="account-setup"') && !str_contains($r['body'],'id="sidebar"') && !str_contains($r['body'],'class="mobile-bottom"'),'Setup screen does not show unusable workspace links');
    $setupToken=token($r); $activationPassword='Activated-password-45678';
    $activateData=['csrf'=>$setupToken,'action'=>'activate','current_password'=>$password,'new_password'=>$activationPassword,'confirm_password'=>$activationPassword];
    check(request('freshAdmin','?page=activate',array_merge($activateData,['csrf'=>'']))['status']===419,'Activation still requires CSRF');
    $invalid=request('freshAdmin','?page=activate',array_merge($activateData,['current_password'=>'Wrong-password-123']));
    check($invalid['status']===422 && str_contains($invalid['body'],'Current password is incorrect.') && str_contains($invalid['body'],'id="account-setup"'),'Incorrect temporary password leaves a visible actionable error');
    check(request('freshAdmin','?page=activate',array_merge($activateData,['confirm_password'=>'Not-the-same-password']))['status']===422,'Mismatched setup passwords are rejected');
    check(request('freshAdmin','?page=activate',array_merge($activateData,['new_password'=>$password,'confirm_password'=>$password]))['status']===422,'Temporary password cannot be reused as new password');
    $r=request('freshAdmin','?page=activate',$activateData);
    check($r['status']===303 && str_contains($r['headers'],'Location: ?page=dashboard'),'Completing setup opens dashboard');
    $activated=$as->record('users',(int)$freshAdmin['id']); check(!$activated['must_change_password'] && $activated['phone']==='09999999999' && password_verify($activationPassword,$activated['password_hash']),'Activation updates credentials and preserves contact information');
    foreach($pageHeadings as $page=>$heading) { $r=request('freshAdmin','?page='.$page); check($r['status']===200 && str_contains($r['body'],'<h1>'.e($heading).'</h1>'),'After first-time setup navigation opens '.$page); }
    check(str_contains(request('freshAdmin','?page=activate')['headers'],'Location: ?page=dashboard'),'Completed account cannot get stuck on setup again');
    $login=request('head'); request('head','',['csrf'=>token($login),'action'=>'login','email'=>$head['email'],'password'=>$password]);
    check(request('head','?page=reports&type=audit')['status']===403,'Supervisor cannot read audit through report selector');
    check(request('head','?page=deployment&activity='.$activity)['status']===200,'Supervisor can review candidates');
    $headCsrf=token(request('head')); $httpActivityData=array_merge($aBase,['title'=>'HTTP end-to-end requirement','starts_at'=>'2035-02-10T08:00','ends_at'=>'2035-02-10T17:00','csrf'=>$headCsrf,'action'=>'activity','return'=>'?page=activities']);
    check(request('head','?page=activities&new=1',$httpActivityData)['status']===303,'Supervisor creates requirement through HTTP');
    $httpActivity=(int)$db->one('SELECT MAX(id) id FROM activities')['id'];
    check(request('head','?page=deployment',['csrf'=>$headCsrf,'action'=>'deploy','activity_id'=>$httpActivity,'nurse_id'=>$n3['id'],'return'=>'?page=deployment'])['status']===303,'Supervisor deploys through HTTP');
    $httpDeployment=(int)$db->one('SELECT MAX(id) id FROM deployments')['id'];
    $login=request('nurse3'); request('nurse3','',['csrf'=>token($login),'action'=>'login','email'=>$n3['email'],'password'=>$password]);
    check(request('nurse3','?page=deployment',['csrf'=>token(request('nurse3')),'action'=>'acknowledge','id'=>$httpDeployment,'return'=>'?page=deployment'])['status']===303,'Assigned nurse acknowledges through HTTP');
    check($as->record('deployments',$httpDeployment)['acknowledged_at']!==null,'HTTP acknowledgment is persisted');
    $pdfFixture=ROOT.'/storage/'.$name.'-attachment.pdf'; file_put_contents($pdfFixture,Reports::pdf(['columns'=>['Note'],'rows'=>[['Test attachment']]],'Test')); $testFiles[]=$pdfFixture;
    $nurseCsrf=token(request('nurse'));
    $uploadData=['csrf'=>$nurseCsrf,'action'=>'leave','type'=>'Vacation Leave','starts_at'=>'2035-03-10T00:00','ends_at'=>'2035-03-11T00:00','reason'=>'Test attachment','attachment'=>new CURLFile($pdfFixture,'application/pdf','support.pdf'),'return'=>'?page=leave'];
    check(request('nurse','?page=leave&new=1',$uploadData)['status']===303,'Nurse submits leave with a PDF attachment');
    $uploadedLeave=$db->one('SELECT * FROM leave_records ORDER BY id DESC LIMIT 1'); if($uploadedLeave['attachment']) $testFiles[]=ROOT.'/storage/uploads/'.$uploadedLeave['attachment'];
    $download=request('nurse','download.php?type=leave&id='.$uploadedLeave['id']); check($download['status']===200 && str_starts_with($download['body'],'%PDF'),'Owner can download a protected attachment');
    check(request('nurse3','download.php?type=leave&id='.$uploadedLeave['id'])['status']===403,'Another nurse cannot download the attachment');
    $badFixture=ROOT.'/storage/'.$name.'-unsafe.txt'; file_put_contents($badFixture,'<?php echo "unsafe";'); $testFiles[]=$badFixture;
    $uploadData['attachment']=new CURLFile($badFixture,'application/pdf','pretend.pdf'); check(request('nurse','?page=leave&new=1',$uploadData)['status']===422,'Disguised executable upload is rejected by MIME validation');
    $photoFixture=ROOT.'/storage/'.$name.'-photo.png'; $photo=imagecreatetruecolor(30,30); imagepng($photo,$photoFixture); imagedestroy($photo); $testFiles[]=$photoFixture;
    check(request('nurse','?page=profile',['csrf'=>$nurseCsrf,'action'=>'profile','phone'=>'09123456789','photo'=>new CURLFile($photoFixture,'image/png','profile.png'),'return'=>'?page=profile'])['status']===303,'Profile image is accepted and re-encoded');
    $photoName=$as->record('users',(int)$n1['id'])['photo']; if($photoName) $testFiles[]=ROOT.'/storage/uploads/'.$photoName;
    check(request('nurse','download.php?type=photo&id='.$n1['id'])['status']===200 && str_ends_with($photoName,'.jpg'),'Processed profile image is served to its owner');
    check(request('nurse3','download.php?type=photo&id='.$n1['id'])['status']===403,'Another nurse cannot fetch the profile photo');
    $profile=request('nurse3','?page=profile');
    check($profile['status']===200 && str_contains($profile['body'],'Second Public School') && str_contains($profile['body'],'Third Public School') && str_contains($profile['body'],'Test School'),'Profile shows home school and all additional school assignments');
    check(str_contains($profile['body'],'Employment status') && str_contains($profile['body'],'Account role') && str_contains($profile['body'],'Account created') && str_contains($profile['body'],'Not recorded'),'Profile includes full personnel fields with explicit missing values');
    check(!str_contains($profile['body'],'Edit personnel details'),'Nurse profile keeps official personnel editing restricted to administrators');
    if(in_array('--browser',$argv,true)) {
        require ROOT.'/tests/Browser.php';
        $chrome=getenv('DALOY_CHROME')?:'C:/Program Files/Google/Chrome/Application/chrome.exe';
        if(!is_file($chrome)) throw new RuntimeException('Set DALOY_CHROME to your Chrome executable.');
        $preview=ROOT.'/storage/preview'; if(!is_dir($preview)) mkdir($preview,0700,true);
        $browser=new Browser($chrome,$preview.'/chrome-profile');
        $db->update('users',(int)$freshAdmin['id'],['must_change_password'=>1]);
        $browser->navigate($baseUrl); $browser->screenshot($preview.'/login-desktop.png',1440,1000);
        $browser->evaluate('document.querySelector("input[name=email]").value='.json_encode($freshAdmin['email']).';document.querySelector("input[name=password]").value='.json_encode($activationPassword).';');
        $browser->click('.login-form button[type=submit]');
        $browser->wait('document.body.dataset.page === "activate"');
        check($browser->evaluate('!document.querySelector(".sidebar") && !!document.querySelector("#account-setup")'),'Chrome first sign-in has a dedicated setup screen');
        $browser->screenshot($preview.'/activation-desktop.png',1440,1000); $browser->screenshot($preview.'/activation-mobile.png',390,844);
        check($browser->evaluate('Math.max(document.documentElement.scrollWidth,document.body.scrollWidth) <= 390'),'Account setup fits phone width');
        $browser->evaluate('document.querySelector("input[name=current_password]").value='.json_encode($activationPassword).';document.querySelector("input[name=new_password]").value="Browser-activated-12345";document.querySelector("input[name=confirm_password]").value="Browser-activated-12345";');
        $browser->click('.activation-form button[type=submit]');
        $browser->wait('!!document.querySelector("#main-content")');
        check($browser->evaluate('document.body.dataset.page === "dashboard"'),'Chrome password setup opens the dashboard');
        $browser->command('Emulation.setDeviceMetricsOverride',['width'=>1440,'height'=>1100,'deviceScaleFactor'=>1,'mobile'=>false]);
        foreach($pageHeadings as $page=>$heading) {
            $browser->click('.sidebar nav a[href="?page='.$page.'"]');
            $browser->wait('document.body.dataset.page === '.json_encode($page));
            check($browser->evaluate('document.querySelector("h1").textContent === '.json_encode($heading).' && document.querySelectorAll(".sidebar nav a.active").length === 1'),'Chrome navigation click opens '.$page);
        }
        $browser->navigate($baseUrl.'?page=dashboard&date=2035-01-10'); $browser->screenshot($preview.'/dashboard-desktop.png',1440,1100);
        check($browser->evaluate('!document.querySelector(".github-connect")'),'Header does not show the standalone GitHub connection button');
        check($browser->evaluate('document.body.dataset.display === "card" && document.querySelector("[data-display-choice=card]").getAttribute("aria-pressed") === "true"'),'Card view is the default overview layout');
        $browser->click('[data-display-choice="list"]');
        check($browser->evaluate('document.body.dataset.display === "list" && document.querySelector("[data-display-choice=list]").getAttribute("aria-pressed") === "true" && new URL(location.href).searchParams.get("display") === "list"'),'List view switch updates layout and URL');
        $browser->click('[data-display-choice="card"]');
        check($browser->evaluate('document.body.dataset.display === "card" && document.querySelector("[data-display-choice=card]").getAttribute("aria-pressed") === "true"'),'Card view switch restores the default layout');
        $browser->evaluate('document.querySelector("#workload-month").value="2035-03";');
        $browser->click('.monthly-chart-filter button');
        $browser->wait('document.querySelector(".monthly-chart-heading p").textContent.includes("March 2035")');
        check($browser->evaluate('document.querySelector(".monthly-nurse-value").textContent.includes("3") && document.querySelector(".monthly-nurse-name").textContent === "Nurse Three"'),'Overview month selector updates the nurse ranking and duty counts');
        $browser->screenshot($preview.'/monthly-nurses-desktop.png',1440,1000);
        $browser->screenshot($preview.'/monthly-nurses-mobile.png',390,844);
        $browser->evaluate('document.querySelector("#monthly-workload").scrollIntoView({block:"center"});');
        $browser->screenshot($preview.'/monthly-nurses-mobile.png',390,844);
        check($browser->evaluate('document.documentElement.scrollWidth <= innerWidth'),'Monthly nurse chart fits mobile width');
        $browser->navigate($baseUrl.'?page=dashboard&date=2035-01-10');
        $browser->screenshot($preview.'/dashboard-desktop.png',1440,1100);
        check($browser->evaluate('document.documentElement.scrollWidth <= innerWidth'),'Desktop dashboard has no horizontal page overflow');
        $browser->evaluate('document.querySelector(".theme-toggle").click()'); check($browser->evaluate('document.documentElement.dataset.theme === "dark"'),'Theme switch works in Chrome');
        $browser->screenshot($preview.'/dashboard-dark.png',1440,1100);
        $browser->evaluate('document.querySelector(".theme-toggle").click()'); $browser->screenshot($preview.'/dashboard-mobile.png',390,844);
        check($browser->evaluate('Math.max(document.documentElement.scrollWidth,document.body.scrollWidth) <= 390'),'Mobile dashboard has no horizontal page overflow');
        $browser->evaluate('document.querySelector(".menu-toggle").click()'); check($browser->evaluate('document.body.classList.contains("nav-open")'),'Mobile navigation opens'); $browser->evaluate('document.querySelector(".menu-toggle").click()');
        $browser->navigate($baseUrl.'?page=schedule&new=1');
        $browser->evaluate('document.querySelector("select[name=nurse_id]").value='.json_encode((string)$n2['id']).';document.querySelector("input[name=starts_at]").value="2035-01-10T08:00";document.querySelector("input[name=ends_at]").value="2035-01-10T17:00";document.querySelector("input[name=ends_at]").dispatchEvent(new Event("change",{bubbles:true}));');
        $browser->wait('document.querySelector(".conflict-preview").textContent.includes("Existing duty")'); check(true,'Live conflict preview works through Fetch API');
        $browser->evaluate('document.querySelector("#shift-preset").value="22:00|06:00";document.querySelector("#shift-preset").dispatchEvent(new Event("change",{bubbles:true}));');
        check($browser->evaluate('document.querySelector("input[name=ends_at]").value === "2035-01-11T06:00"'),'Overnight shift preset advances end date');
        $browser->navigate($baseUrl.'?page=deployment&activity='.$activity); $browser->screenshot($preview.'/deployment-desktop.png',1440,1100);
        $browser->navigate($baseUrl.'?page=calendar&view=month&date=2035-01-10'); $browser->screenshot($preview.'/calendar-desktop.png',1440,1100);
        $db->run('UPDATE notifications SET read_at=? WHERE user_id=?',[now(),$freshAdmin['id']]);
        $as->notify((int)$freshAdmin['id'],'School health visit scheduled','Your next school visit has been added. Review the schedule for the time and location.','?page=schedule');
        $as->notify((int)$freshAdmin['id'],'Personnel required','A school health activity needs nursing support. View the deployment details.','?page=deployment');
        $browser->navigate($baseUrl.'?page=notifications');
        $browser->screenshot($preview.'/notifications-desktop.png',1440,1000);
        $browser->screenshot($preview.'/notifications-mobile.png',390,844);
        check($browser->evaluate('document.documentElement.scrollWidth <= innerWidth'),'Notification inbox fits mobile width');
        $browser->click('.inbox-item-actions button');
        $browser->wait('document.querySelectorAll(".inbox-item.is-unread").length === 1');
        check(true,'Notification mark-as-read works in the browser');
        $browser->navigate($baseUrl.'?page=profile');
        $browser->screenshot($preview.'/profile-desktop.png',1440,1100);
        $browser->screenshot($preview.'/profile-mobile.png',390,844);
        check($browser->evaluate('document.documentElement.scrollWidth <= innerWidth'),'Complete profile fits mobile width');
        check($browser->evaluate('document.querySelectorAll(".person-profile-fields dt").length === 10 && !!document.querySelector(".profile-home-school")'),'Profile displays personnel, competencies, and assignment sections in browser');
        $browser->navigate($baseUrl.'?page=users&edit='.$n3['id']);
        check($browser->evaluate('document.querySelectorAll(".school-assignments input[type=checkbox]:checked").length === 2'),'Nurse editor restores multiple selected schools');
        $browser->evaluate('const search=document.querySelector(".school-assignment-search");search.value="Third";search.dispatchEvent(new Event("input",{bubbles:true}));');
        check($browser->evaluate('document.querySelectorAll(".school-assignment-option:not([hidden])").length === 1 && document.querySelectorAll(".school-assignments input[type=checkbox]:checked").length === 2'),'School search filters results without clearing selected schools');
        $browser->evaluate('document.querySelector(".school-assignments").scrollIntoView({block:"center"});');
        $browser->screenshot($preview.'/nurse-schools-mobile.png',390,844);
        $browser->evaluate('document.querySelector(".school-assignments").scrollIntoView({block:"center"});');
        $browser->screenshot($preview.'/nurse-schools-mobile.png',390,844);
        check($browser->evaluate('document.documentElement.scrollWidth <= innerWidth'),'Multiple-school editor fits mobile width');
        $browser->evaluate('document.querySelector(".school-assignment-option:not([hidden]) input").checked=false;');
        $browser->click('.editor button[type=submit]');
        $browser->wait('!document.querySelector(".school-assignments")');
        check(count($db->all('SELECT * FROM nurse_locations WHERE nurse_id=?',[$n3['id']]))===1,'Nurse editor saves school selections through the browser');
        $browser->close(); $browser=null;
    }
    require ROOT.'/app/AuroraSchools.php';
    check(import_aurora_schools($db)===243,'Complete Aurora snapshot imports');
    $imported=$db->one("SELECT * FROM locations WHERE name='Abuleg ES'");
    $db->update('locations',(int)$imported['id'],['contact_person'=>'Local coordinator','active'=>0]);
    check(import_aurora_schools($db)===0,'Aurora import is safe to repeat');
    $retained=$db->one('SELECT * FROM locations WHERE id=?',[$imported['id']]);
    check($retained['contact_person']==='Local coordinator' && !$retained['active'],'Repeat import preserves local edits and status');
    $r=request('admin','?page=locations&q=104443');
    check($r['status']===200 && str_contains($r['body'],'Abuleg ES') && !str_contains($r['body'],'Abungan ES'),'Directory searches official school IDs');
    $as->notify((int)$admin['id'],'Notification test update','A new school visit is ready.','?page=schedule');
    $note=$db->one('SELECT id FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 1',[$admin['id']]);
    $otherNote=$db->insert('notifications',['user_id'=>$n3['id'],'title'=>'Private test update','message'=>'Only for this nurse','link'=>'?page=schedule','created_at'=>now()]);
    $inbox=request('admin','?page=notifications&status=unread');
    check($inbox['status']===200 && str_contains($inbox['body'],'Notification test update') && !str_contains($inbox['body'],'Private test update'),'Unread inbox shows only the signed-in user’s updates');
    check(request('admin','?page=notifications',['csrf'=>token($inbox),'action'=>'read_notification','id'=>$note['id'],'return'=>'?page=notifications&status=unread'])['status']===303,'One notification can be marked as read');
    check(!str_contains(request('admin','?page=notifications&status=unread')['body'],'Notification test update') && str_contains(request('admin','?page=notifications&status=read')['body'],'Notification test update'),'Read and unread filters reflect the saved state');
    request('admin','?page=notifications',['csrf'=>token($inbox),'action'=>'read_notification','id'=>$otherNote,'return'=>'?page=notifications']);
    check($db->one('SELECT read_at FROM notifications WHERE id=?',[$otherNote])['read_at']===null,'Mark-as-read cannot change another user’s notification');
    $baler=$db->one("SELECT id FROM municipalities WHERE name='Baler'")['id'];
    $r=request('admin','?page=locations&municipality_id='.$baler.'&location_type=School');
    check($r['status']===200 && str_contains($r['body'],'Baler CS') && !str_contains($r['body'],'Abuleg ES'),'Directory filters schools by municipality');
    $r=request('admin','?page=locations&p=2');
    check($r['status']===200 && str_contains($r['body'],'Page 2'),'Aurora directory supports pagination');
    $login=request('throttle'); for($i=0;$i<10;$i++) request('throttle','',['csrf'=>token($login),'action'=>'login','email'=>'missing@example.test','password'=>'Wrong-password-123']);
    check(request('throttle','',['csrf'=>token($login),'action'=>'login','email'=>'missing@example.test','password'=>'Wrong-password-123'])['status']===429,'Repeated login failure is throttled');
    preg_match_all('/^.*PHP (?:Warning|Fatal error|Parse error|Notice):.*$/m',file_get_contents($log),$serverErrors);
    check(!$serverErrors[0],'HTTP test server emitted no PHP warnings or errors'.($serverErrors[0]?': '.implode("\n",$serverErrors[0]):''));
    echo "\n$passed checks passed.\n";
} catch(Throwable $e) { $failed=true; fwrite(STDERR,(string)$e."\n"); }
finally {
    if($browser) $browser->close();
    if(is_resource($process)) { proc_terminate($process); proc_close($process); }
    foreach($cookies as $file) if(is_file($file)) unlink($file);
    foreach($testFiles as $file) if(is_file($file)) unlink($file);
    if(is_file($configFile)) unlink($configFile);
    if(is_file($log)) { if($failed) fwrite(STDERR,implode('',array_slice(file($log),-35))); unlink($log); }
    if(is_dir($testConfig['session_path'])) { foreach(glob($testConfig['session_path'].'/sess_*') as $file) unlink($file); rmdir($testConfig['session_path']); }
    // The name is generated above, never supplied by configuration or user input.
    if(preg_match('/^daloy_test_[a-f0-9]{10}$/D',$name)) $server->exec("DROP DATABASE `$name`");
    if($restoreName && preg_match('/^daloy_test_[a-f0-9]{10}$/D',$restoreName)) $server->exec("DROP DATABASE `$restoreName`");
}
exit($failed?1:0);
