<?php
$isLeave=$page==='leave';
page_heading('WORKFORCE AVAILABILITY',$isLeave?'Leave & unavailability':'Availability',$isLeave?'Submit leave requests and review their scheduling impact.':'Record availability for a specific interval. Existing official assignments always take priority.',add_link('?page='.$page.'&new=1',$isLeave?'Submit request':'Record availability'));
if(isset($_GET['new'])) {
    $r=$error?$_POST:[];
    ?><section class="card editor"><h2><?=$isLeave?'New leave / unavailability request':'Record an availability interval'?></h2><?php form_start($isLeave?'leave':'availability','?page='.$page); nurse_field($r); if($isLeave) select_field('type','Request type',choices(['Vacation Leave','Sick Leave','Official Leave','Other Leave','Unavailability']),$r['type']??''); else select_field('status','Availability status',choices(['Available','Off Duty','Unavailable']),$r['status']??''); time_fields($r); textarea('reason',$isLeave?'Reason (collect only operationally necessary information)':'Remarks',$r['reason']??'',$isLeave); if($isLeave): ?><label>Supporting attachment (optional, max 5 MB)<input type="file" name="attachment" accept=".pdf,.jpg,.jpeg,.png"></label><?php endif; form_end('?page='.$page,$isLeave?'Submit for review':'Save availability'); ?></section><?php
}
if(!$isLeave) {
    $day=(string)($_GET['date']??date('Y-m-d')); [$start,$end]=$service->window(['starts_at'=>$day.' 00:00','ends_at'=>date('Y-m-d',strtotime($day.' +1 day')).' 00:00']);
    ?><form method="get" class="filters"><input type="hidden" name="page" value="availability"><?php input('date','Workforce date',$day,'date'); ?><button>View availability</button></form><section class="card"><div class="section-heading"><h2>Workforce status</h2><p>“Available” means no recorded blockers during the selected day. Confirm exact times in the deployment center.</p></div><div class="table-wrap"><table><thead><tr><th>Nurse</th><th>Home assignment</th><th>Status</th><th>Recorded commitments</th></tr></thead><tbody><?php foreach($service->workforce($start,$end) as $u): ?><tr><td><?=e($u['name'])?></td><td><?=e($u['location_name']?:'—')?><small><?=e($u['district_name'])?></small></td><td><?=badge($u['status'])?></td><td><?php foreach($u['conflicts'] as $c): ?><small><?=e($c['label'].' · '.dt($c['starts_at']).' – '.dt($c['ends_at']))?></small><?php endforeach ?><?=$u['conflicts']?'':'No recorded blockers'?></td></tr><?php endforeach ?></tbody></table></div></section><?php
}
$table=$isLeave?'leave_records':'availability_records'; $where=$service->manager()?'1=1':'r.nurse_id='.(int)$user['id'];
$status=(string)($_GET['status']??''); if($status!=='' && !in_array($status,['Submitted','Approved','Rejected','Cancelled','Available','Off Duty','Unavailable'])) throw new DomainException('Invalid status.',422);
$params=[]; if($status!=='') { $where.=' AND r.status=?'; $params[]=$status; }
$rows=$db->all("SELECT r.*,u.name nurse_name FROM $table r JOIN users u ON u.id=r.nurse_id WHERE $where ORDER BY r.id DESC LIMIT 26 OFFSET $offset",$params);
if($isLeave): ?><form class="filters" method="get"><input type="hidden" name="page" value="leave"><?php select_field('status','Review status',choices(['Submitted','Approved','Rejected','Cancelled']),$status,false); ?><button>Filter</button></form><?php endif ?>
<section class="card"><div class="section-heading"><h2><?=$isLeave?'Requests & review history':'Availability records'?></h2></div><?php if(!$rows): empty_state('No records yet','Use the button above to add a record.'); else: ?><div class="table-wrap"><table><thead><tr><th>Nurse</th><th>Period</th><th><?=$isLeave?'Request':'Remarks'?></th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach(array_slice($rows,0,25) as $r): ?><tr><td><?=e($r['nurse_name'])?></td><td><?=range_label($r)?><small>Ends <?=e(dt($r['ends_at']))?></small></td><td><?php if($isLeave): ?><strong><?=e($r['type'])?></strong><?php endif ?><small><?=e($r['reason'])?></small><?php if($isLeave && $r['attachment']): ?><a href="download.php?type=leave&id=<?=$r['id']?>">Supporting attachment ↗</a><?php endif ?></td><td><?=badge($r['status'])?><?php if($isLeave && $r['reviewed_at']): ?><small>Reviewed <?=e(dt($r['reviewed_at']))?></small><small><?=e($r['review_note'])?></small><?php endif ?></td><td><?php if($isLeave && $service->manager() && $r['status']==='Submitted'): ?><details><summary>Review request</summary><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="review_leave"><input type="hidden" name="id" value="<?=$r['id']?>"><input type="hidden" name="return" value="?page=leave"><?php select_field('status','Decision',choices(['Approved','Rejected'])); textarea('review_note','Review note'); ?><button class="primary small">Save decision</button></form></details><?php endif; if(!$isLeave || $r['status']!=='Approved' || $service->manager()) cancel_control($table,$r,'?page='.$page); ?></td></tr><?php endforeach ?></tbody></table></div><?php endif ?></section><?php pagination(count($rows),$pageNum);
