<?php
$date=(string)($_GET['date']??date('Y-m-d')); [$start,$end]=$service->window(['starts_at'=>$date.' 00:00','ends_at'=>date('Y-m-d',strtotime($date.' +1 day')).' 00:00']);
$workforce=$service->workforce($start,$end); $counts=array_count_values(array_column(array_filter($workforce,fn($u)=>$u['active']),'status'));
$active=count(array_filter($workforce,fn($u)=>$u['active'])); $available=$counts['Available']??0;
$roster=$service->roster(['starts_at'=>$start,'ends_at'=>$end]);
$activities=$db->all("SELECT a.*,l.name location_name,(SELECT COUNT(*) FROM deployments d WHERE d.activity_id=a.id AND d.status<>'Cancelled') assigned FROM activities a JOIN locations l ON l.id=a.location_id WHERE a.status='Open' AND a.ends_at>? ORDER BY a.starts_at LIMIT 4",[now()]);
page_heading('WORKFORCE AT A GLANCE',($service->manager()?'Your workforce, in flow.':'Hello, '.preg_replace('/^Demo /','',explode(' ',$user['name'])[0]).'.'),$service->manager()?'A clearer picture of your people, their duty, and where they’re needed.':'Your duty schedule, upcoming assignments, and updates in one place.',add_link('?page=schedule&new=1','Add schedule'));
?>
<?php if($user['role']==='admin'):
    $setupSteps=[
        ['label'=>'Add districts / areas','url'=>'?page=configuration&tab=districts&new=1','done'=>(bool)$db->one('SELECT id FROM districts WHERE active=1 LIMIT 1')],
        ['label'=>'Add schools & duty locations','url'=>'?page=locations&new=1','done'=>(bool)$db->one('SELECT id FROM locations WHERE active=1 LIMIT 1')],
        ['label'=>'Create nursing personnel accounts','url'=>'?page=users&new=1','done'=>(bool)$db->one("SELECT id FROM users WHERE active=1 AND role='nurse' LIMIT 1")],
    ];
    if(count(array_filter($setupSteps,fn($step)=>$step['done']))<count($setupSteps)): ?>
    <section class="card workspace-setup" aria-labelledby="workspace-setup-title">
        <h2 id="workspace-setup-title">Set up your workforce</h2>
        <p>Add your official districts, locations, and nursing personnel to start scheduling.</p>
        <ol><?php foreach($setupSteps as $step): ?><li><?php if($step['done']): ?><span><?=e($step['label'])?></span><?=badge('Ready')?><?php else: ?><a href="<?=e($step['url'])?>"><?=e($step['label'])?> <span aria-hidden="true">→</span></a><?php endif ?></li><?php endforeach ?></ol>
    </section>
    <?php endif; endif ?>
<section class="overview-banner"><div><span class="eyebrow">SCHOOLS DIVISION OFFICE OF AURORA</span><h2>Every assignment connects to better care.</h2><p><?=e(date('l, F j, Y',strtotime($date)))?> <span>•</span> <?=count($roster)?> assignment<?=count($roster)===1?'':'s'?> on the roster</p></div><form method="get" class="date-switch"><input type="hidden" name="page" value="dashboard"><label class="sr-only" for="dashboard-date">Workforce date</label><input id="dashboard-date" type="date" name="date" value="<?=e($date)?>" required><button>View day</button></form></section>
<section class="stats-grid" aria-label="Workforce summary"><?php foreach([['Active nurses',$active,'nurses','blue','In your '.($service->manager()?'workforce':'profile')],['On duty / scheduled',($counts['On Duty']??0)+($counts['Scheduled']??0),'calendar','teal','Duty during selected day'],['Potentially available',$available,'availability','green','No conflicts during the day'],['Deployed / on leave',($counts['Deployed']??0)+($counts['On Leave']??0),'deployment','violet',($counts['Deployed']??0).' deployed · '.($counts['On Leave']??0).' on leave']] as [$label,$value,$ico,$color,$note]): ?><article class="stat-card"><div><span><?=e($label)?></span><div class="stat-icon <?=$color?>"><?=icon($ico)?></div></div><strong class="stat-value"><?=$value?></strong><small><?=e($note)?></small></article><?php endforeach ?></section>
<?php if($service->manager()) require __DIR__.'/monthly-nurse-chart.php'; ?>
<div class="dashboard-columns"><div><section class="card roster-card"><div class="section-heading"><div><span class="eyebrow">DAILY OPERATIONS</span><h2><?= $service->manager()? 'Duty roster':'My assignments' ?></h2></div><a href="?page=schedule">View schedule <?=icon('arrow')?></a></div><?php roster_table(array_slice($roster,0,6)); ?><div class="card-foot"><span class="live-dot"></span> Based on recorded schedules and approved assignments</div></section>
<?php if($service->manager()): ?><section class="card"><div class="section-heading"><div><span class="eyebrow">LOCATION COVERAGE</span><h2>Care where it’s needed</h2></div><a href="?page=locations">All locations →</a></div><p class="muted inset">Distinct nurses assigned during this day; partial-day assignments may leave time gaps.</p><?php $locations=$db->all('SELECT * FROM locations WHERE active=1 AND required_nurses>0 ORDER BY name LIMIT 6'); if(!$locations) empty_state('Set your coverage targets','Add a required nurse count to your schools and duty locations.'); foreach($locations as $l): $ids=[]; foreach($roster as $r) if($r['location_id']==$l['id']) $ids[$r['nurse_id']]=true; $covered=count($ids); ?><div class="coverage-row"><div class="location-icon"><?=icon('locations')?></div><div><strong><?=e($l['name'])?></strong><small><?=$covered?> / <?=$l['required_nurses']?> nurses assigned</small></div><?=badge($covered>=$l['required_nurses']?'Covered':'Needs '.($l['required_nurses']-$covered))?></div><?php endforeach ?></section><?php endif ?></div>
<div><section class="card"><div class="section-heading"><div><span class="eyebrow">COMING UP</span><h2>Activities & staffing</h2></div><?=icon('activities')?></div><?php if(!$activities) empty_state('No upcoming activities','New personnel requirements will appear here.'); foreach($activities as $a): ?><article class="activity-preview"><div class="activity-date"><strong><?=date('d',strtotime($a['starts_at']))?></strong><span><?=date('M',strtotime($a['starts_at']))?></span></div><div><h3><?=e($a['title'])?></h3><p><?=e($a['location_name'])?></p><?=badge($a['assigned'] >= $a['required_nurses']?'Fully staffed':'Needs '.($a['required_nurses']-$a['assigned']).' nurses')?><?php if($service->manager()): ?><a href="?page=deployment&activity=<?=$a['id']?>">Review candidates →</a><?php endif ?></div></article><?php endforeach ?></section>
<section class="card available-card"><div class="section-heading"><div><span class="eyebrow">READY TO SUPPORT</span><h2>Potentially available</h2></div><span class="pill-count"><?=$available?></span></div><p class="muted inset">Availability is checked again for the exact deployment interval.</p><?php $free=array_slice(array_filter($workforce,fn($u)=>$u['status']==='Available'),0,4); if(!$free) empty_state('No free personnel for this day','Review exact times in the deployment center.'); foreach($free as $u): ?><div class="available-person"><div class="person"><?=avatar($u['name'])?><div><strong><?=e($u['name'])?></strong><small><?=e($u['district_name']??'Unassigned district')?></small></div></div><span class="live-dot"></span></div><?php endforeach ?><?php if($service->manager()): ?><a class="button full" href="?page=deployment">Open deployment center <?=icon('arrow')?></a><?php endif ?></section></div></div>
