<?php
if($page==='activities') {
    page_heading('PERSONNEL REQUIREMENTS','Activities & events','Plan official activities, set staffing needs, and coordinate assignments.',add_link('?page=activities&new=1','New requirement'));
    if(isset($_GET['new']) || isset($_GET['edit'])) {
        $r=isset($_GET['edit'])?$service->record('activities',(int)$_GET['edit']):[]; if($error && ($_POST['action']??'')==='activity') $r=array_merge($r,$_POST);
        ?><section class="card editor"><h2><?=isset($r['id'])?'Edit requirement':'Request nursing personnel'?></h2><?php form_start('activity','?page=activities',$r); input('title','Activity / requirement title',$r['title']??''); select_field('location_id','Destination / venue',options('locations'),$r['location_id']??''); time_fields($r); input('organizer','Organizer',$r['organizer']??'','text',false); input('required_nurses','Nurses required',$r['required_nurses']??1,'number',true,'min="1" max="1000"'); select_field('reason_id','Deployment reason',options('deployment_reasons'),$r['reason_id']??''); input('required_skill','Required competency (optional)',$r['required_skill']??'','text',false); textarea('instructions','Reason, instructions & remarks',$r['instructions']??''); form_end('?page=activities','Save requirement'); ?></section><?php
    }
    $status=($_GET['status']??'')==='Cancelled'?'Cancelled':'Open';
    ?><div class="tabs"><a class="<?=$status==='Open'?'selected':''?>" href="?page=activities">Open requirements</a><a class="<?=$status==='Cancelled'?'selected':''?>" href="?page=activities&status=Cancelled">Cancelled</a></div><?php
    $rows=$db->all("SELECT a.*,l.name location_name,r.name reason_name,(SELECT COUNT(*) FROM deployments d WHERE d.activity_id=a.id AND d.status<>'Cancelled') assigned FROM activities a JOIN locations l ON l.id=a.location_id JOIN deployment_reasons r ON r.id=a.reason_id WHERE a.status=? ORDER BY a.starts_at DESC LIMIT 26 OFFSET $offset",[$status]);
    ?><div class="activity-grid"><?php if(!$rows) empty_state('No personnel requirements','Create an activity or staffing request to find available nurses.'); foreach(array_slice($rows,0,25) as $r): ?><article class="card activity-card"><div class="section-heading"><span class="activity-date"><strong><?=date('d',strtotime($r['starts_at']))?></strong><span><?=date('M',strtotime($r['starts_at']))?></span></span><?=badge($r['status']==='Cancelled'?'Cancelled':($r['assigned']>=$r['required_nurses']?'Fully staffed':'Needs '.($r['required_nurses']-$r['assigned'])) )?></div><h2><?=e($r['title'])?></h2><p><?=e($r['location_name'])?></p><p><?=range_label($r)?></p><dl class="detail-list"><dt>Organizer</dt><dd><?=e($r['organizer']?:'—')?></dd><dt>Reason</dt><dd><?=e($r['reason_name'])?></dd><dt>Competency</dt><dd><?=e($r['required_skill']?:'No specific requirement')?></dd><dt>Staffing</dt><dd><?=$r['assigned']?> / <?=$r['required_nurses']?> assigned</dd></dl><p><?=nl2br(e($r['instructions']))?></p><div class="card-actions"><a class="button primary small" href="?page=deployment&activity=<?=$r['id']?>">Review candidates →</a><?php if($r['status']!=='Cancelled'): ?><a href="?page=activities&edit=<?=$r['id']?>">Edit</a><?php cancel_control('activities',$r,'?page=activities'); endif ?></div></article><?php endforeach ?></div><?php pagination(count($rows),$pageNum); return;
}
page_heading('COORDINATE & DEPLOY','Deployment center',$service->manager()?'Find the right personnel. Review eligibility. Confirm official assignments.':'Review and acknowledge your official duty assignments.',$service->manager()?add_link('?page=activities&new=1','New requirement'):'');
if($service->manager()) {
    $requirements=$db->all("SELECT id,title FROM activities WHERE status='Open' ORDER BY starts_at DESC");
    ?><form method="get" class="filters"><input type="hidden" name="page" value="deployment"><?php select_field('activity','Select a personnel requirement',array_column($requirements,'title','id'),$_GET['activity']??'',false); ?><button class="primary">Find candidates</button><a href="?page=deployment">All deployments</a></form><?php
    if(!empty($_GET['activity'])) {
        $a=$service->record('activities',(int)$_GET['activity']); $location=$service->record('locations',(int)$a['location_id']); $assigned=$db->one("SELECT COUNT(*) n FROM deployments WHERE activity_id=? AND status<>'Cancelled'",[$a['id']])['n'];
        ?><section class="requirement-summary card"><div><span class="eyebrow">DEPLOYMENT REQUIREMENT #<?=$a['id']?></span><h2><?=e($a['title'])?></h2><p><?=e($location['name'])?> · <?=e(dt($a['starts_at']))?> – <?=e(dt($a['ends_at']))?></p><p><?=nl2br(e($a['instructions']))?></p><p><strong>Required competency:</strong> <?=e($a['required_skill']?:'No specific requirement')?></p></div><div class="staffing-count"><strong><?=$assigned?><span>/<?=$a['required_nurses']?></span></strong><small>NURSES ASSIGNED</small></div></section>
        <section class="card"><div class="section-heading"><div><h2>Potential deployment candidates</h2><p>Eligibility includes the full requested interval. The authorized supervisor makes the final decision.</p></div></div><div class="table-wrap"><table><thead><tr><th>Nurse / home assignment</th><th>Competencies</th><th>Eligibility & conflicts</th><th>Action</th></tr></thead><tbody><?php foreach($service->candidates((int)$a['id']) as $c): ?><tr><td><div class="person"><?=avatar($c['name'])?><div><strong><?=e($c['name'])?></strong><small><?=e($c['location_name']?:'No home location')?></small></div></div></td><td><?=e($c['specialization'])?><small><?=e($c['skills'])?></small></td><td><?=badge($c['eligible']?'Available':'Unavailable')?><?php foreach($c['reasons'] as $reason): ?><small><?=e($reason)?></small><?php endforeach ?></td><td><?php if($c['eligible'] && $assigned<$a['required_nurses']): ?><details class="deploy-confirm"><summary class="button small primary">Review & deploy</summary><div class="confirm-body"><h3>Confirm official deployment</h3><p><strong><?=e($c['name'])?></strong><br><?=e($a['title'])?><br><?=e($location['name'])?><br><?=e(dt($a['starts_at']))?> – <?=e(dt($a['ends_at']))?></p><p><?=e($service->record('deployment_reasons',(int)$a['reason_id'])['name'])?></p><p><?=nl2br(e($a['instructions']))?></p><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="deploy"><input type="hidden" name="activity_id" value="<?=$a['id']?>"><input type="hidden" name="nurse_id" value="<?=$c['id']?>"><input type="hidden" name="return" value="?page=deployment&activity=<?=$a['id']?>"><button class="primary">Confirm deployment</button></form></div></details><?php else: ?><span class="muted"><?=$assigned>=$a['required_nurses']?'Fully staffed':'Not eligible'?></span><?php endif ?></td></tr><?php endforeach ?></tbody></table></div></section><?php
    }
}
$where=$service->manager()?'1=1':'d.nurse_id='.(int)$user['id']; $params=[]; if(!empty($_GET['activity'])) { $where.=' AND d.activity_id=?'; $params[]=(int)$_GET['activity']; }
$rows=$db->all("SELECT d.*,u.name nurse_name,a.title,l.name location_name,h.name authorized_name FROM deployments d JOIN users u ON u.id=d.nurse_id JOIN users h ON h.id=d.authorized_by JOIN activities a ON a.id=d.activity_id JOIN locations l ON l.id=d.location_id WHERE $where ORDER BY d.created_at DESC,d.id DESC LIMIT 26 OFFSET $offset",$params);
?><section class="card"><div class="section-heading"><h2>Assignments & deployment history</h2><span class="muted">Original records are retained</span></div><?php if(!$rows): empty_state('No deployments yet','Confirmed assignments and acknowledgments will appear here.'); else: ?><div class="table-wrap"><table><thead><tr><th>Nurse / activity</th><th>Destination & time</th><th>Authorization</th><th>Acknowledgment</th><th>Details / action</th></tr></thead><tbody><?php foreach(array_slice($rows,0,25) as $r): ?><tr><td><strong><?=e($r['nurse_name'])?></strong><small><?=e($r['title'])?></small><small>Deployment #<?=$r['id']?></small></td><td><?=e($r['location_name'])?><?=range_label($r)?></td><td><?=e($r['authorized_name'])?><small><?=e(dt($r['created_at']))?></small></td><td><?=badge($r['status'])?><small><?=$r['acknowledged_at']?e(dt($r['acknowledged_at'])):($r['status']==='Cancelled'?'—':'Awaiting acknowledgment')?></small></td><td><details><summary>Assignment details</summary><dl class="detail-list"><dt>Original home assignment</dt><dd><?=e($r['original_assignment'])?></dd><dt>Reason</dt><dd><?=e($r['reason'])?></dd><dt>Instructions</dt><dd><?=nl2br(e($r['instructions']))?></dd><?php if($r['status']==='Cancelled'): ?><dt>Cancellation</dt><dd><?=e($r['cancellation_reason'])?> · <?=e(dt($r['cancelled_at']))?></dd><?php endif ?></dl></details><?php if(!$service->manager() && !$r['acknowledged_at'] && $r['status']!=='Cancelled') simple_action('acknowledge',(int)$r['id'],'Acknowledge assignment','?page=deployment'); if($service->manager()) cancel_control('deployments',$r,'?page=deployment'); ?></td></tr><?php endforeach ?></tbody></table></div><?php endif ?></section><?php pagination(count($rows),$pageNum);
