<?php
require_once ROOT.'/app/Reports.php';
$type=$page==='audit'?'audit':(string)($_GET['type']??'daily'); $types=Reports::TYPES; if($user['role']!=='admin') unset($types['audit']);
if(!isset($types[$type])) throw new DomainException('This report is unavailable.',403);
if(!isset($_GET['from'])) {
    $from=match($type){'daily','availability'=>date('Y-m-d'),'weekly'=>date('Y-m-d',strtotime('monday this week')),default=>date('Y-m-01')};
    $to=match($type){'daily','availability'=>date('Y-m-d'),'weekly'=>date('Y-m-d',strtotime('sunday this week')),default=>date('Y-m-t')};
    $filters['starts_at']=$from.' 00:00:00'; $filters['ends_at']=date('Y-m-d',strtotime($to.' +1 day')).' 00:00:00';
}
page_heading('INSIGHTS & ACCOUNTABILITY',$page==='audit'?'Audit trail':'Reports','Filter operational records and export a dated copy for administrative use.');
?><form class="filters report-filters" method="get"><input type="hidden" name="page" value="<?=e($page)?>"><?php if($page!=='audit') select_field('type','Report', $types,$type); input('from','From',$from,'date'); input('to','Through',$to,'date'); if($page!=='audit') { select_field('nurse_id','Nurse',options('users',"role='nurse'"),$_GET['nurse_id']??'',false); select_field('district_id','District / area',options('districts','1=1'),$_GET['district_id']??'',false); select_field('location_id','Location',options('locations','1=1'),$_GET['location_id']??'',false); select_field('municipality_id','Municipality',options('municipalities','1=1'),$_GET['municipality_id']??'',false); if(in_array($type,['activity','deployment'])) select_field('activity_id','Activity',array_column($db->all('SELECT id,title FROM activities ORDER BY starts_at DESC'),'title','id'),$_GET['activity_id']??'',false); } ?><button class="primary">Generate report</button></form>
<?php $report=Reports::build($service,$type,$filters); $query=http_build_query(array_merge($_GET,['type'=>$type,'from'=>$from,'to'=>$to])); ?>
<section class="card report-card"><div class="section-heading"><div><h2><?=e($types[$type])?></h2><p><?=e($from)?> – <?=e($to)?> · <?=count($report['rows'])?> records · generated <?=e(now())?></p></div><div class="button-group"><a class="button small" href="export.php?<?=e($query)?>&format=print" target="_blank" rel="noopener">Print</a><a class="button small" href="export.php?<?=e($query)?>&format=pdf">PDF ↓</a><a class="button small primary" href="export.php?<?=e($query)?>&format=xlsx">Excel ↓</a></div></div>
<?php if(!$report['rows']): empty_state('No records for this report',$type==='conflicts'?'No overlapping assignments were found. Conflicting new records are blocked before saving.':'Adjust the reporting period or filters.'); else: ?><div class="table-wrap"><table><thead><tr><?php foreach($report['columns'] as $column): ?><th><?=e($column)?></th><?php endforeach ?></tr></thead><tbody><?php foreach(array_slice($report['rows'],$offset,25) as $row): ?><tr><?php foreach($row as $value): ?><td><?php if(strlen((string)$value)>180): ?><details><summary><?=e(mb_substr((string)$value,0,90))?>…</summary><pre><?=e($value)?></pre></details><?php else: ?><?=e($value)?><?php endif ?></td><?php endforeach ?></tr><?php endforeach ?></tbody></table></div><?php endif ?><div class="card-foot">Reports are limited to 5,000 records per source. Narrow the date range for larger histories. PDF uses transliterated text; Excel preserves Unicode.</div></section><?php pagination(count($report['rows'])-$offset,$pageNum);
