<?php
page_heading('PLAN & COORDINATE',$page==='calendar'?'Workforce calendar':($service->manager()?'Master schedule':'My schedule'),'Authorized duty and deployment assignments, together in one view.',add_link('?page=schedule&new=1','Add schedule'));
if($page==='schedule' && (isset($_GET['new']) || isset($_GET['edit']))) {
    $r=isset($_GET['edit'])?$service->record('schedules',(int)$_GET['edit']):[]; if($r) $service->own((int)$r['nurse_id']);
    if($error && ($_POST['action']??'')==='schedule') $r=array_merge($r,$_POST);
    ?><section class="card editor"><h2><?=isset($r['id'])?'Edit duty schedule':'New duty schedule'?></h2><p class="muted">Enter an authorized assignment. Conflicts are checked before the record is saved.</p><?php form_start('schedule','?page=schedule',$r); nurse_field($r); select_field('duty_type_id','Duty type',options('duty_types'),$r['duty_type_id']??''); select_field('location_id','Duty location',options('locations'),$r['location_id']??'');
    $shifts=$db->all('SELECT * FROM shifts WHERE active=1 ORDER BY name'); ?><label>Use a shift (optional)<select id="shift-preset"><option value="">Custom times</option><?php foreach($shifts as $s): ?><option value="<?=e($s['start_time'].'|'.$s['end_time'])?>"><?=e($s['name'].' · '.$s['start_time'].'–'.$s['end_time'])?></option><?php endforeach ?></select></label><?php time_fields($r); textarea('remarks','Remarks',$r['remarks']??''); ?><div class="span-2 conflict-preview" aria-live="polite"></div><?php form_end('?page=schedule',isset($r['id'])?'Save schedule':'Create schedule'); ?></section><?php
}
if($page==='schedule') {
    filter_form('schedule',$from,$to); $rows=$service->roster($filters); echo '<section class="card">'; roster_table(array_slice($rows,$offset,25),true); echo '</section>'; pagination(count($rows)-$offset,$pageNum); return;
}
$view=in_array($_GET['view']??'month',['day','week','month'],true)?($_GET['view']??'month'):'month';
$date=(string)($_GET['date']??date('Y-m-d')); $dateObj=DateTimeImmutable::createFromFormat('!Y-m-d',$date); if(!$dateObj || $dateObj->format('Y-m-d')!==$date) throw new DomainException('Invalid calendar date.',422);
$startObj=match($view){'day'=>$dateObj,'week'=>$dateObj->modify('monday this week'),default=>$dateObj->modify('first day of this month')};
$endObj=match($view){'day'=>$startObj->modify('+1 day'),'week'=>$startObj->modify('+7 days'),default=>$startObj->modify('+1 month')};
$calFilters=$_GET+['starts_at'=>$startObj->format('Y-m-d H:i:s'),'ends_at'=>$endObj->format('Y-m-d H:i:s')]; $rows=$service->roster($calFilters);
$navBase=$view==='month'?$startObj:$dateObj;
$previous=$navBase->modify('-1 '.$view)->format('Y-m-d'); $next=$navBase->modify('+1 '.$view)->format('Y-m-d');
?><form method="get" class="filters"><input type="hidden" name="page" value="calendar"><?php input('date','Date',$date,'date'); select_field('view','View', ['day'=>'Day','week'=>'Week','month'=>'Month'],$view); if($service->manager()) { select_field('nurse_id','Nurse',options('users',"role='nurse'"),$_GET['nurse_id']??'',false); select_field('district_id','District / area',options('districts','1=1'),$_GET['district_id']??'',false); } select_field('location_id','Location',options('locations','1=1'),$_GET['location_id']??'',false); select_field('municipality_id','Municipality',options('municipalities','1=1'),$_GET['municipality_id']??'',false); select_field('duty_type_id','Duty type',options('duty_types','1=1'),$_GET['duty_type_id']??'',false); select_field('status','Status',choices(['Scheduled','Assigned','Acknowledged','Cancelled']),$_GET['status']??'',false); ?><button>Apply filters</button></form>
<section class="card"><div class="section-heading"><h2><?=e($view==='month'?$dateObj->format('F Y'):($view==='week'?'Week of '.$startObj->format('F j, Y'):$dateObj->format('l, F j, Y')))?></h2><div class="button-group"><?php foreach([$previous=>'← Previous',date('Y-m-d')=>'Today',$next=>'Next →'] as $day=>$label): ?><a class="button small" href="?<?=e(http_build_query(array_merge($_GET,['page'=>'calendar','date'=>$day,'view'=>$view])))?>"><?=e($label)?></a><?php endforeach ?></div></div>
<?php if($view==='day'): roster_table($rows,true); ?><div class="inset"><h3>Availability for this day</h3><div class="availability-chips"><?php foreach($service->workforce($startObj->format('Y-m-d H:i:s'),$endObj->format('Y-m-d H:i:s')) as $u): ?><div><?=e($u['name'])?> <?=badge($u['status'])?></div><?php endforeach ?></div></div><?php else:
    $gridStart=$view==='month'?$startObj->modify('monday this week'):$startObj; $gridEnd=$view==='month'?$endObj->modify('-1 day')->modify('sunday this week')->modify('+1 day'):$endObj;
    ?><div class="calendar-grid"><?php foreach(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'] as $day): ?><div class="calendar-weekday"><?=$day?></div><?php endforeach ?><?php for($cursor=$gridStart;$cursor<$gridEnd;$cursor=$cursor->modify('+1 day')): $day=$cursor->format('Y-m-d'); $nextDay=$cursor->modify('+1 day')->format('Y-m-d'); $items=array_filter($rows,fn($r)=>$r['starts_at']<$nextDay.' 00:00:00' && $r['ends_at']>$day.' 00:00:00'); ?><div class="calendar-cell <?=$day===date('Y-m-d')?'today':''?> <?=$cursor<$startObj||$cursor>=$endObj?'outside':''?>"><a class="day-number" href="?<?=e(http_build_query(array_merge($_GET,['page'=>'calendar','view'=>'day','date'=>$day])))?>"><?=$cursor->format('j')?></a><?php foreach(array_slice($items,0,$view==='week'?12:3) as $r): ?><a class="calendar-event <?=$r['source']==='deployments'?'deployment-event':''?>" href="?<?=e(http_build_query(array_merge($_GET,['page'=>'calendar','view'=>'day','date'=>$day])))?>" title="<?=e($r['duty_name'].' · '.$r['location_name'])?>"><b><?=e(date('H:i',strtotime($r['starts_at'])))?></b> <?=e($r['nurse_name'])?><small><?=e($r['duty_name'])?></small></a><?php endforeach ?><?php if(count($items)>($view==='week'?12:3)): ?><a class="more-events" href="?page=calendar&view=day&date=<?=$day?>">+<?=count($items)-($view==='week'?12:3)?> more</a><?php endif ?></div><?php endfor ?></div><?php endif ?></section>
