<?php
if($page==='profile') { require __DIR__.'/profile.php'; return; }
page_heading('PEOPLE & ACCESS',$page==='users'?'User accounts':'Nursing personnel',$page==='users'?'Manage secure access and official personnel records.':'Your nursing team, home assignments, and recorded competencies.',$user['role']==='admin'?add_link('?page=users&new=1','Add account'):'');
if($page==='users' && (isset($_GET['new'])||isset($_GET['edit']))) {
    $r=isset($_GET['edit'])?$service->record('users',(int)$_GET['edit']):[]; if($error && ($_POST['action']??'')==='user') $r=array_merge($r,$_POST);
    ?><section class="card editor"><h2><?=isset($r['id'])?'Edit account':'Create account'?></h2><?php form_start('user','?page=users',$r); input('name','Full name',$r['name']??'','text',true,'maxlength="120"'); input('email','Email address',$r['email']??'','email'); select_field('role','Role',['nurse'=>'Nurse','head'=>'Nurse Head / Supervisor','admin'=>'Administrator'],$r['role']??'nurse'); select_field('active','Account status',[1=>'Active',0=>'Inactive'],$r['active']??1); input('employee_number','Employee number',$r['employee_number']??'','text',false); input('designation','Position / designation',$r['designation']??'Nurse'); select_field('district_id','Assigned district / area',options('districts'),$r['district_id']??'',false); select_field('location_id','Home school / office',options('locations'),$r['location_id']??'',false); school_assignments_field($r); select_field('employment_status','Employment status',choices(['Permanent','Contractual','Job Order','Temporary']),$r['employment_status']??'Permanent'); input('phone','Contact number',$r['phone']??'','tel',false); input('specialization','Specialization',$r['specialization']??'','text',false); input('password',isset($r['id'])?'Reset password (leave blank to retain)':'Temporary password','','password',!isset($r['id']),'autocomplete="new-password" minlength="12" maxlength="72"'); textarea('skills','Relevant skills / competencies',$r['skills']??''); ?><p class="help span-2">Users must change a temporary password at first sign-in. Share it through your organization’s approved channel.</p><?php form_end('?page=users','Save account'); ?></section><?php
}
$q=trim((string)($_GET['q']??'')); $params=[]; $where=$page==='nurses'?"u.role='nurse'":'1=1'; if($q!=='') { $where.=' AND (u.name LIKE ? OR u.email LIKE ? OR u.employee_number LIKE ?)'; $params=array_fill(0,3,'%'.$q.'%'); }
$district=(int)($_GET['district_id']??0); if($district) { $where.=' AND u.district_id=?'; $params[]=$district; }
?><form class="filters" method="get"><input type="hidden" name="page" value="<?=e($page)?>"><?php input('q','Search people',$q,'search',false,'placeholder="Name, email or employee number"'); select_field('district_id','District / area',options('districts','1=1'),$district,false); ?><button>Search</button><a href="?page=<?=e($page)?>">Reset</a></form><?php
$rows=$db->all("SELECT u.id,u.name,u.email,u.employee_number,u.phone,u.designation,u.role,u.active,u.specialization,u.skills,u.employment_status,d.name district_name,l.name location_name FROM users u LEFT JOIN districts d ON d.id=u.district_id LEFT JOIN locations l ON l.id=u.location_id WHERE $where ORDER BY u.name LIMIT 26 OFFSET $offset",$params);
?><section class="card"><?php if(!$rows): empty_state('No personnel found','Create accounts or adjust your search filters.'); else: ?><div class="table-wrap"><table><thead><tr><th>Personnel</th><th>Assigned schools / office</th><th>Competencies</th><th>Status</th><th>Details</th></tr></thead><tbody><?php foreach(array_slice($rows,0,25) as $r): ?><tr><td><div class="person"><?=avatar($r['name'])?><div><strong><?=e($r['name'])?></strong><small><?=e($r['designation'])?> · <?=e($r['employee_number']?:'No employee number')?></small></div></div></td><td><?=e(implode('; ',array_column($service->assignedLocations((int)$r['id']),'name'))?:'Unassigned')?><small><?=e($r['district_name'])?></small></td><td><?=e($r['specialization']?:'—')?><small><?=e($r['skills'])?></small></td><td><?=badge($r['active']?'Active':'Inactive')?><small><?=e(ucfirst($r['role']))?></small></td><td><details><summary>Contact & details</summary><p><?=e($r['email'])?><br><?=e($r['phone'])?><br><?=e($r['employment_status'])?></p></details><?php if($user['role']==='admin'): ?><a href="?page=users&edit=<?=$r['id']?>">Edit account</a><?php endif ?></td></tr><?php endforeach ?></tbody></table></div><?php endif ?></section><?php pagination(count($rows),$pageNum);
